config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'home', to: 'pages#home', as: 'home'
  get 'about', to: 'pages#about', as:'about'
  get 'ysun3', to: 'pages#ysun3', as: 'ysun3'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # render 'home.html.erb'
  end


  def about
    # render 'about.html.erb'
  end

  def ysun3
    # render 'ysun3.html.erb
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<ul>
<li><%= link_to 'ysun3', ysun3_path%></li>
</ul>
<p>
<%= link_to 'Home', home_path %>

</p>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<h2>Menu</h2>
<ul>
<li><%= link_to 'About', about_path %>,</li>
</ul>

app/views/pages/ysun3.html.erb
<h1>Rain Sun</h>



<p>
Hello! Welcome to my page!
</p>
<p>
Here is my homepage: <%= link_to 'https://github.com/Rain-Sun'%>
</p>
<%=image_tag("A-kitten-with-ears-flattened-or-back-angry.jpg")%>
<p>
<%= link_to 'Home', home_path %>

</p>